# whitelist gh-pages explicitly, because it's not a default branch - http://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - gh-pages

language: node_js

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
node_js:
  - "0.10"
  
script:
  # http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Default-Test-Script
  - npm test
  